### ISSUE TITLE
Neuer Link für Raspberrymatic Version

### ISSUE THREAD

**Issue by fraeggle** [Baenker/Pruefung-CCU-Firmware#3]
Hi. Der "alte Link
https://gitcdn.xyz/repo/jens-maus/RaspberryMatic/master/release/LATEST-VERSION.js
liefert nicht mehr die neue Version.
Laut Jens Maus soll in zukunft https://raspberrymatic.de/LATEST-VERSION.js genommen werden.
Auszug aus dem Forum:
"Das gibt es schon länger nicht mehr. War nicht zuverlässig. Inzwischen verwendet RaspberryMatic selbst die folgende URL:

https://raspberrymatic.de/LATEST-VERSION.js
"
Habs bei mir in deinem Script geändert und funktioniert.

:-D

Gruß Peter

**Comment by Baenker** [comment]
Link angepasst
