### ISSUE TITLE
Provided config URL is wrong

### ISSUE THREAD

**Issue by Madaraxa** [Baenker/Pruefung-CCU-Firmware#4]
Hi,
Sadly i dont understand much about "scripting". 
Maybe it's all my fault.
I get the following errors at start of the script:
`<html><body>

javascript.0 | 2022-02-13 08:40:21.402 | error | at Script.runInContext (vm.js:144:12)
javascript.0 | 2022-02-13 08:40:21.402 | error | at script.js.CCUneueFirmware:287:3
javascript.0 | 2022-02-13 08:40:21.401 | error | at script.js.CCUneueFirmware:285:5
javascript.0 | 2022-02-13 08:40:21.401 | error | at func_Version (script.js.CCUneueFirmware:132:5)
javascript.0 | 2022-02-13 08:40:21.401 | error | at wrap (/opt/iobroker/node_modules/axios/lib/helpers/bind.js:9:15)
javascript.0 | 2022-02-13 08:40:21.400 | error | at Axios.request (/opt/iobroker/node_modules/axios/lib/core/Axios.js:40:11)
javascript.0 | 2022-02-13 08:40:21.400 | error | script.js.CCUneueFirmware: Error: Provided config url is not valid

</body>
</html>`

**Comment by Baenker** [comment]
welche Version vom Script?
Was ist konfiguriert? Erste Zeilen im Script z. B. Zeile 36

Auf jeden Fall aktuelle Version nutzen.

**Comment by Madaraxa** [comment]
Hi.
Ich hatte die Version 1.17 (wie diese auch noch vor 5 Tagen "aktuell" war. Jetzt mit der 1.19 geht wieder alles.
Vielen Dank
