### ISSUE TITLE
2 Fehler beim Iobroker Start. Nach Skriptneustart i.O.

### ISSUE THREAD

**Issue by Madaraxa** [Baenker/Pruefung-CCU-Firmware#5]
Hey,
ich habe gerade meinen Iobroker neu gestartet. Habe mittlerweile Javaskript 8.0.3 drauf und bekomme beim Start folgende Fehler:

`javascript.0 | 2024-04-14 16:16:29.911 | error | at func_Version (script.js.CCUneueFirmware:173:49)
-- | -- | -- | --
javascript.0 | 2024-04-14 16:16:29.909 | error | script.js.CCUneueFirmware: TypeError: Cannot read properties of undefined (reading 'Version')`

Wenn ich das Skript manuell beende und dann neu starte kommen keine Fehler im Log.
Muss ich mir Gedanken machen? :)

**Comment by Baenker** [comment]
Zeig mal die beiden Datenpunkte… Also einmal der von der CCU was dort drin steht und einmal den selbst erstellten. Ggf mal etwas in den selbst erstellen reinschreiben z. B. 1.0

**Comment by Madaraxa** [comment]
im Javascript Objekt "Verfuegbare_CCU-Firmware" steht 3.75.6.20240316"
ich hoffe, das waren die beiden Datenpunkte, die du meintest

EDIT: Sorry, jetzt hab ich den richtigen
FIRMWARE_VERSION im hm-rega Adapter "3.75.6.20240316"
Wie gesagt hatte ich den iobroker komplett neu gestartet. Evtl. hat der irgendwie das Skript schneller laufen lassen, als ein Datenpunkt gefüllt werden konnte? Oder sowas in der Art? Oder hm-rega Adapter war noch nicht online als das Skript schon gelaufen ist?

**Comment by Baenker** [comment]
Denkbar. Ab und an kommt aber auch ein Fehler wenn die Version Online nicht abgerufen werden kann. Auf jeden Fall solltest Du mal über ein Update nachdenken…

Beobachte das ganze mal etwas. Wenn Du keinen Fehler mehr bekommst sollte es auf jeden Fall jetzt passen

**Comment by Madaraxa** [comment]
> Denkbar. Ab und an kommt aber auch ein Fehler wenn die Version Online nicht abgerufen werden kann. Auf jeden Fall solltest Du mal über ein Update nachdenken…

Was meinst Du damit? Also was für ein Update? Die Adapter sind aktuell und die raspberrymatic auch, oder übersehe ich was?

**Comment by Baenker** [comment]
Du hattest eben noch unterschiedliche Versionsnr genannt. Jetzt sind sie gleich…

**Comment by Madaraxa** [comment]
Ah. Ja, sorry. Hab den falschen datenpunkt zunächst geschrieben. (regaVersion)
Danke dir für die Hilfe
